version: "3"

services:
 haproxy: 
  image: "haproxy:2.0-alpine"
  restart: always
  volumes:
      - "./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro"
  networks:
    net1:
      ipv4_address: 172.20.0.50
      aliases:
         - haproxy
 keepalived:
  image: "osixia/keepalived:2.0.19"
  cap_add:
    - NET_ADMIN
    - NET_BROADCAST
    - NET_RAW
  network_mode: host
  restart: always
  volumes:
    - "./keepalived/keepalived.conf:/usr/local/etc/keepalived/keepalived.conf:ro"
 web:
  image: "nginx:stable-alpine"
  networks:
    net1:
      aliases:
        - web
  volumes:
    - "./web/index.html:/usr/share/nginx/html/index.html:ro"
networks:
  net1:
    ipam:
      config:
        - subnet: 172.20.0.0/24

